array_width = 100
attr_fn_like_width = 100
chain_width = 100
edition = "2021"
fn_call_width = 100
max_width = 120
merge_derives = false
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
single_line_if_else_max_width = 100
single_line_let_else_max_width = 100
struct_lit_width = 100
struct_variant_width = 100
tab_spaces = 4
use_field_init_shorthand = true
use_try_shorthand = true
