name: Rust

on:
  push:
    branches: []
  pull_request:
    branches: []

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Setup - Install Nightly
      run: rustup toolchain install nightly
    - name: Setup - Install Clippy
      run: rustup component add clippy --toolchain nightly
    - name: Setup - Install RustFmt
      run: rustup component add rustfmt --toolchain nightly

    - name: Action - Compile binary
      run: cargo build --verbose
    - name: Action - Run Clippy
      run: cargo clippy --verbose
    - name: Action - Run tests
      run: cargo test --verbose
    - name: Action - Validate formatting
      run: cargo fmt --all -- --check
